import {
    Entity, PrimaryGeneratedColumn, Column,
    CreateDateColumn, ManyToOne, JoinColumn,
} from 'typeorm';
import { ChatSession } from './chat-session.entity';

export type MessageSender = 'visitor' | 'admin';

@Entity('chat_messages')
export class ChatMessage {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column()
    sessionId: string;

    @ManyToOne(() => ChatSession, (s) => s.messages, { onDelete: 'CASCADE' })
    @JoinColumn({ name: 'sessionId' })
    session: ChatSession;

    @Column({ type: 'text' })
    content: string;

    @Column({ type: 'varchar', default: 'visitor' })
    sender: MessageSender;

    @Column({ type: 'varchar', default: 'text' })
    messageType: 'text' | 'audio' | 'file' | 'reminder';

    @Column({ type: 'varchar', nullable: true, default: null })
    audioUrl: string | null;

    @Column({ type: 'varchar', nullable: true, default: null })
    fileUrl: string | null;

    @Column({ type: 'varchar', nullable: true, default: null })
    fileName: string | null;

    @Column({ type: 'varchar', nullable: true, default: null })
    fileType: string | null;

    @Column({ type: 'int', nullable: true, default: null })
    fileSize: number | null;

    @Column({ default: false })
    read: boolean;

    /** True when this admin reply was generated by the AI bot */
    @Column({ default: false })
    isBot: boolean;

    @CreateDateColumn()
    createdAt: Date;
}
